### ISSUE TITLE
PE pages

### ISSUE THREAD

**Issue by yassinrais** [saferwall/saferwall-ui#1]
- [ ] DOS : 00000083cd4a91dec60b43e541c66c19302643e9104af2ae409412eac8f7d048
- [ ] Rich : 0000072c3a0b1a61957de8b3f56ea3bbcbd5d0b48228a78a93475db4aa354b0c
- [ ] NT : 00000083cd4a91dec60b43e541c66c19302643e9104af2ae409412eac8f7d048
- [ ] Sections : 00000083cd4a91dec60b43e541c66c19302643e9104af2ae409412eac8f7d048
- [ ] Export : 000049925c578e5a0883e7d1a8257c1a44feab8f7d9972ace8d0e3fb96612a4c
- [ ] Imports : 00000083cd4a91dec60b43e541c66c19302643e9104af2ae409412eac8f7d048
- [ ] Exceptions : ffb8182763c23b8abcef35e85291422a1d6d165a0f4407bc68ffed0a58a2d03c
- [ ] Certificate : 0500078bb01e1352009d4b965fc91b6f773aa167de5f82236489b7c4b0eeca11
- [ ] Relocations : 000049925c578e5a0883e7d1a8257c1a44feab8f7d9972ace8d0e3fb96612a4c
- [ ] IAT : 00000083cd4a91dec60b43e541c66c19302643e9104af2ae409412eac8f7d048
- [ ] Resources : 000049925c578e5a0883e7d1a8257c1a44feab8f7d9972ace8d0e3fb96612a4c
- [ ] Debugs
  - Code view: 0000072c3a0b1a61957de8b3f56ea3bbcbd5d0b48228a78a93475db4aa354b0c
  - POGO:  00015FA066E590A25F190B53DA7A7D0E150140C6DB70D1DC895A7BD91CF2D5D9
  - REPRO: 00015FA066E590A25F190B53DA7A7D0E150140C6DB70D1DC895A7BD91CF2D5D9
  - Ex Dll Char: 001794E3DB23D2806283766BBABB9EC7314DEFB62B9E00C44361D4FA2A111722
  - VC Feature: 000022e0f57b26fd89351da2a933666df483ed8bc04067557823e9659c21e84d
  - FPO: 6896C1F21CC9A5BC17E2E2FB645669AE708CB378C63E5EEF11B3E95527F3DA32
- [ ] TLS (000049925c578e5a0883e7d1a8257c1a44feab8f7d9972ace8d0e3fb96612a4c)
- [x] Load config
  - GFIDS: 00015fa066e590a25f190b53da7a7d0e150140c6db70d1dc895a7bd91cf2d5d9
  - CFGIAT: 00015fa066e590a25f190b53da7a7d0e150140c6db70d1dc895a7bd91cf2d5d9
  - SEH: 0006b2c5db896c76bd326cf8637ad32f1ce374203a4a92d11081d2389eb97495
  - DVRT: c9c2fbe9a26480f9c7714e65c01df9e18530547314f01a322b3e274d19f598a3
  - Long Jump: 00E868DB17A95AC54A96BA192B379FB820E0ACA1F7B34DED9D10EEFB341AFC58
  - Enclave: 045679986c4ecb5d3148b3303076edf2fec47f52c775f9f077106830426dc6d0
  - Volatile Metadata: 0187981c2d832ac9ec6442c8b717784b3292bc6c268e7ffbd546e6a6e5c3c5d1
  - CHPE:  93e3c0020f98708620e4c6102d8f12f8038112daaac2fe2a5d6e6d71260b1938
- [ ] Bound imports
  - 0000c36a79954fa0333e8831e699076b6cd1371d7f588d0301e97d0364edf7b5
  - 00000205a4cfdb3b04374dd84bb638e13517f1a8095ec99b97c80da10e3bcc2e // no forwarded refs case
- [ ] Delay imports (000049925c578e5a0883e7d1a8257c1a44feab8f7d9972ace8d0e3fb96612a4c)
- [x] CLR (2b3ead4f40779324d728c8970721b3af78f8085877e73e1ae163085515ed285a)
- [x] COFF (46f7cc1c408cee484887bbad232f81f33ac3e7d2c9a3fe97a4020b4905ed318e)

**Comment by yassinrais** [comment]
@LordNoteworthy Is there anything else that needs to be changed?

**Comment by LordNoteworthy** [comment]
that should be it, did you find any fields that are still pascal case ?

**Comment by sickl8** [comment]
Can't get files for these (404)
- [ ] Debugs
  - FPO
  - Ex Dll Char
- [ ] Load Config
  - SEH
  - DVRT
  - Long Jump
  - Enclave
  - Volatile Metadata
  - CHPE
