### ISSUE TITLE
[Fix] Views & Style

### ISSUE THREAD

**Issue by yassinrais** [saferwall/saferwall-ui#23]
- [x] Open static analysis menu by default
- [x] Dynamic Analysis _in a line_ (font size)

**Comment by yassinrais** [comment]
- [ ] PE: Header view
- [ ] Add a bollean (liked) in summary view saferwall/saferwall-api#7

**Comment by LordNoteworthy** [comment]
@yassinrais: + the share and rescan button in the summary:

![image](https://user-images.githubusercontent.com/5129564/150042560-032b723b-906f-481e-ad01-a8c12d8e5af1.png)

**Comment by LordNoteworthy** [comment]
+ White background for the multiav widget:
![image](https://user-images.githubusercontent.com/5129564/150044053-4328518d-6928-4537-bdd4-db3fed5d48e3.png)

**Comment by yassinrais** [comment]
- [ ] File Summary Signature : Add a field for file signature saferwall-api#8
