### ISSUE TITLE
[feature] button copy text on hover

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall-ui#34]
One of the handy features to have is the ability to copy text when mouse is over some object.

We can start with any text inside an html table.

**Comment by yassinrais** [comment]
Demo
![image](https://user-images.githubusercontent.com/25354731/152554243-9b4aa788-37d5-4208-a304-3f93311cde26.png)
![image](https://user-images.githubusercontent.com/25354731/152554266-51c913f4-50f8-400e-8c7b-36b9590f7cf4.png)

**Comment by yassinrais** [comment]
@LordNoteworthy where i should add the copy button ?
