### ISSUE TITLE
UI Bugs (beta)

### ISSUE THREAD

**Issue by JLL32** [saferwall/saferwall-ui#49]
profile follow not working and it seems that has to do with the use of undefined data in the form enhance args (it should be formData instead)
![image](https://github.com/user-attachments/assets/0c76e22e-67bd-4809-9a04-8e11904289c7)

**Comment by ayoubfaouzi** [comment]
- Change Password not working:

![image](https://github.com/user-attachments/assets/ce38d0da-710c-49af-a548-c594755c8697)

**Comment by ayoubfaouzi** [comment]
- [  ]  Change Email (if you use the same email as logged in email, it shows success, otherwise error)

**Comment by ayoubfaouzi** [comment]
- [ ] Delete Account

**Comment by sickl8** [comment]
> * Change Password not working:
> 
> ![image](https://private-user-images.githubusercontent.com/5129564/393429790-ce38d0da-710c-49af-a548-c594755c8697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MzA1NTksIm5iZiI6MTczMzUzMDI1OSwicGF0aCI6Ii81MTI5NTY0LzM5MzQyOTc5MC1jZTM4ZDBkYS03MTBjLTQ5YWYtYTU0OC1jNTk0NzU1Yzg2OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMDAxMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRjZTM2NjI0YzRmZWZlOTdiZjMwZTMwZjhjMGJlNjk5ZDc0ZDRlZDBmNzIzZjg5Y2JhMzNjZjJhYjI4ZWIzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fGyTkHZJFjmGabnYd17ah9jVLQatrbgK_tNadMmr-T0)

fixed
