### ISSUE TITLE
API Calls page

### ISSUE THREAD

**Issue by yassinrais** [saferwall/saferwall-ui#9]

**Comment by LordNoteworthy** [comment]
## Behavior Reports

In addition to the `file` , `user` and `activity` resources in our REST APIs, we have introduced the `behavior` resource.

Each dynamic scan will create a new behavior resource object. One file can have multiple dynamic scan reports.

**Example:**

```json
"behavior_reports": {
    "9203dc96-b5b6-4ab5-ad80-5278475490c7": {
      "args": "",
      "country": "USA",
      "dest_path": "%USERPROFILE%//Downloads//partridgelike.exe",
      "id": "9203dc96-b5b6-4ab5-ad80-5278475490c7",
      "os": "Windows 7 64-bit",
      "sandbox_ver": "0.5.0",
      "timeout": 30,
      "timestamp": 1690090465
    },
    "05494c75-cd58-4469-91af-710bae719cc1": {
      "args": "",
      "country": "USA",
      "dest_path": "%USERPROFILE%//Downloads//subsoil.exe",
      "id": "05494c75-cd58-4469-91af-710bae719cc1",
      "os": "Windows 7 64-bit",
      "sandbox_ver": "0.5.0",
      "timeout": 30,
      "timestamp": 1690091030
    },
...
}
```

When the user is browsing a file object in the UI and he goes into one of menus that involves dynamic analysis, a default behavior report ID is available in the `file` object at the field named:

```json
  "behavior_report_id": "3a4339ec-104a-4b1d-8920-c12ad8e797e0",
```

`behavior_report_id` is now available in `summary/` for your convenience.

### Endpoint for getting API Calls: 

```
`GET /v1/behaviors/<guid>/api-trace
```

This returns a paginated list of API calls objects. Each object looks like this:

```json
  {
      "args": [
        {
          "value": "0x76d40000"
        },
        {
          "value": "VirtualAlloc"
        }
      ],
      "name": "GetProcAddress",
      "pid": "0xb90",
      "ret": "0x57e0",
      "tid": "0x6cc",
      "ts": 30505832510
    },
```

It maps 1:1 with the table in the UI of API Trace. When an entry in the table is clicked, we display the arguments of the API:

Inside the `args`, you have 2 cases:
1. `value` contains the value of the parameter. `buff_id` is an optional field, when it exists, it means there is a huge buffer and the ID represents the key from S3 so you can download it.
2. or  you have `value_in` and `value_out`. The can also have an optional field `buff_id_in` and `buff_id_out`.

Those `value` fields can be either a string or an array of bytes.

**Comment by LordNoteworthy** [comment]
@yassinrais Use this file hash as an example: 

b102ed1018de0b7faea37ca86f27ba3025c0c70f28417ac3e9ef09d32617f801

**Comment by LordNoteworthy** [comment]
- [ ] During pagination arguments disappeared.
